poc-assets/config/routes.rb
PocAssets::Application.routes.draw do

  resources :themes

  root :to => 'themes#index'

end

poc-assets/app/models/image.rb
class Image
  include Mongoid::Document

  field :filename, type: String
  field :data, type: String

  embedded_in :theme, :inverse_of => :images
end

poc-assets/app/models/theme.rb
class Theme
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :css , type: String
  field :js  , type: String

  embeds_many :images

  accepts_nested_attributes_for :images
  after_save :compile_assets

  def compile_assets
    assets = ThemeAssets.new(self)
    assets.compile_all
  end
end

poc-assets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

poc-assets/app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  def index
    @themes = Theme.all
  end

  def new
    @theme = Theme.new
    @theme.images.build
  end

  def show
    @theme = Theme.find(params[:id])
    @assets = ThemeAssets.new(@theme)
  end

  def create
    @theme = Theme.new(params[:theme])
    @theme.save
    update_images
    redirect_to themes_path
  end

  def edit
    @theme = Theme.find(params[:id])
    @theme.images.build
  end

  def update
    @theme = Theme.find(params[:id])
    @theme.update_attributes(params[:theme])
    update_images
   redirect_to themes_path
  end

  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy if @theme
    redirect_to themes_path
  end

  private
  def update_images
    (params[:images] || []).each do |image|
      @theme.images << Image.new(filename: image.original_filename, data: File.read(image.tempfile))
    end
    @theme.save
  end
end

poc-assets/app/helpers/application_helper.rb
module ApplicationHelper
end

poc-assets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PocAssets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= yield :stylesheets %>
  <%= javascript_include_tag "application" %>
  <%= yield :javascripts %>
  <%= csrf_meta_tags %>
</head>
<body id="css-zen-garden">

<%= yield %>

</body>
</html>

poc-assets/app/views/themes/_form.html.erb
<%= form_for @theme, :html => { :multipart => true } do |f| %>
  <p><%= f.label :name %> </p>
  <p><%= f.text_field :name %></p>

  <br/>
  <p><%= f.label :css %> </p>
  <p><%= f.text_area :css, rows: 10, cols: 150  %></p>

  <br/>
  <p><%= f.label :js %> </p>
  <p><%= f.text_area :js, rows: 10, cols: 150 %></p>

  <p><%= f.label :images %> </p>
  <% 5.times do |i| %>
    <%= file_field_tag('images[]') %><br/>
  <% end %>

  <p><%= f.label :current_images %> </p>

  <% @theme.images.each do |image| %>
    <% unless image.new_record? %>
      <p><%= image.filename %></p>
    <% end %>
  <% end %>

  <p><%= f.submit %></p>
<% end %>

poc-assets/app/views/themes/edit.html.erb
<h2>Edit Theme</h2>
<%= render 'form' %>

poc-assets/app/views/themes/index.html.erb
<h2>Listing themes</h2>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

  <% @themes.each do |theme| %>
    <tr>
      <td><%= theme.name %></td>
      <td><%= link_to 'Show', theme %></td>
      <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
      <td><%= link_to 'Destroy', theme, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New theme', new_theme_path %>

poc-assets/app/views/themes/new.html.erb
<h2>New Theme</h2>
<%= render 'form' %>

poc-assets/app/views/themes/show.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag @assets.stylesheet_file %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag @assets.javascript_file %>
<% end %>

<!--

  View source is a feature, not a bug. Thanks for your curiosity and
  interest in participating!

  Here are the submission guielines for the new and improved csszengarden.com:

  - CSS3? Of course! Prefix for ALL browsers where necessary.
  - go responsive; test your layout at multiple screen sizes.
  - your browser testing baseline: IE9+, recent Chrome/Firefox/Safari, and iOS/Android
  - Graceful degradation is acceptable, and in fact highly encouraged.
  - use classes for styling. Don't use ids.
  - web fonts are cool, just make sure you have a license to share the files

  And a few tips on building your CSS file:

  - use :first-child, :last-child and :nth-child to get at non-classed elements
  - use ::before and ::after to create pseudo-elements for extra styling
  - use multiple background images to apply as many as you need to any element
  - use the Kellum Method for image replacement, if still needed. http://goo.gl/GXxdI
  - don't rely on the extra divs at the bottom. Use ::before and ::after instead.


  -->
  <div class="page-wrapper">

    <section class="intro" id="zen-intro">
      <header role="banner">
        <h1>CSS Zen Garden</h1>
        <h2>The Beauty of <abbr title="Cascading Style Sheets">CSS</abbr> Design</h2>
      </header>

      <div class="summary" id="zen-summary">
        <p>A demonstration of what can be accomplished through <abbr title="Cascading Style Sheets">CSS</abbr>-based design. Select any style sheet from the list to load it into this page.</p>
        <p>Download the example <a href="" title="This page's source HTML code, not to be modified.">html file</a> and <a href="" title="This page's sample CSS, the file you may modify.">css file</a></p>
      </div>

      <div class="preamble" id="zen-preamble">
        <h3>The Road to Enlightenment</h3>
        <p>Littering a dark and dreary road lay the past relics of browser-specific tags, incompatible <abbr title="Document Object Model">DOM</abbr>s, broken <abbr title="Cascading Style Sheets">CSS</abbr> support, and abandoned browsers.</p>
        <p>We must clear the mind of the past. Web enlightenment has been achieved thanks to the tireless efforts of folk like the <abbr title="World Wide Web Consortium">W3C</abbr>, <abbr title="Web Standards Project">WaSP</abbr>, and the major browser creators.</p>
        <p>The CSS Zen Garden invites you to relax and meditate on the important lessons of the masters. Begin to see with clarity. Learn to use the time-honored techniques in new and invigorating fashion. Become one with the web.</p>
      </div>
    </section>

    <div class="main supporting" id="zen-supporting" role="main">
      <div class="explanation" id="zen-explanation">
        <h3>So What is This About?</h3>
        <p>There is a continuing need to show the power of <abbr title="Cascading Style Sheets">CSS</abbr>. The Zen Garden aims to excite, inspire, and encourage participation. To begin, view some of the existing designs in the list. Clicking on any one will load the style sheet into this very page. The <abbr title="HyperText Markup Language">HTML</abbr> remains the same, the only thing that has changed is the external <abbr title="Cascading Style Sheets">CSS</abbr> file. Yes, really.</p>
        <p><abbr title="Cascading Style Sheets">CSS</abbr> allows complete and total control over the style of a hypertext document. The only way this can be illustrated in a way that gets people excited is by demonstrating what it can truly be, once the reins are placed in the hands of those able to create beauty from structure. Designers and coders alike have contributed to the beauty of the web; we can always push it further.</p>
      </div>

      <div class="participation" id="zen-participation">
        <h3>Participation</h3>
        <p>Strong visual design has always been our focus. You are modifying this page, so strong <abbr title="Cascading Style Sheets">CSS</abbr> skills are necessary too, but the example files are commented well enough that even <abbr title="Cascading Style Sheets">CSS</abbr> novices can use them as starting points. Please see the <a href="" title="A listing of CSS-related resources"><abbr title="Cascading Style Sheets">CSS</abbr> Resource Guide</a> for advanced tutorials and tips on working with <abbr title="Cascading Style Sheets">CSS</abbr>.</p>
        <p>You may modify the style sheet in any way you wish, but not the <abbr title="HyperText Markup Language">HTML</abbr>. This may seem daunting at first if you&#8217;ve never worked this way before, but follow the listed links to learn more, and use the sample files as a guide.</p>
        <p>Download the sample <a href="/zengarden-sample.html" title="This page's source HTML code, not to be modified.">HTML</a> and <a href="/zengarden-sample.css" title="This page's sample CSS, the file you may modify.">CSS</a> to work on a copy locally. Once you have completed your masterpiece (and please, don&#8217;t submit half-finished work) upload your <abbr title="Cascading Style Sheets">CSS</abbr> file to a web server under your control. <a href="" title="Use the contact form to send us your CSS file">Send us a link</a> to an archive of that file and all associated assets, and if we choose to use it we will download it and place it on our server.</p>
      </div>

      <div class="benefits" id="zen-benefits">
        <h3>Benefits</h3>
        <p>Why participate? For recognition, inspiration, and a resource we can all refer to showing people how amazing <abbr title="Cascading Style Sheets">CSS</abbr> really can be. This site serves as equal parts inspiration for those working on the web today, learning tool for those who will be tomorrow, and gallery of future techniques we can all look forward to.</p>
      </div>

      <div class="requirements" id="zen-requirements">
        <h3>Requirements</h3>
        <p>Where possible, we would like to see mostly <abbr title="Cascading Style Sheets, levels 1 and 2">CSS 1 &amp; 2</abbr> usage. <abbr title="Cascading Style Sheets, levels 3 and 4">CSS 3 &amp; 4</abbr> should be limited to widely-supported elements only, or strong fallbacks should be provided. The CSS Zen Garden is about functional, practical <abbr title="Cascading Style Sheets">CSS</abbr> and not the latest bleeding-edge tricks viewable by 2% of the browsing public. The only real requirement we have is that your <abbr title="Cascading Style Sheets">CSS</abbr> validates.</p>
        <p>Luckily, designing this way shows how well various browsers have implemented <abbr title="Cascading Style Sheets">CSS</abbr> by now. When sticking to the guidelines you should see fairly consistent results across most modern browsers. Due to the sheer number of user agents on the web these days &#8212; especially when you factor in mobile &#8212; pixel-perfect layouts may not be possible across every platform. That&#8217;s okay, but do test in as many as you can. Your design should work in at least IE9+ and the latest Chrome, Firefox, iOS and Android browsers (run by over 90% of the population).</p>
        <p>We ask that you submit original artwork. Please respect copyright laws. Please keep objectionable material to a minimum, and try to incorporate unique and interesting visual themes to your work. We&#8217;re well past the point of needing another garden-related design.</p>
        <p>This is a learning exercise as well as a demonstration. You retain full copyright on your graphics (with limited exceptions, see <a href="">submission guidelines</a>), but we ask you release your <abbr title="Cascading Style Sheets">CSS</abbr> under a Creative Commons license identical to the <a href="" title="View the Zen Garden's license information.">one on this site</a> so that others may learn from your work.</p>
        <p>Bandwidth graciously donated by <a href="">mediatemple</a>. Now available: <a href="">Zen Garden, the book</a>.</p>
      </div>

      <footer>
        <a href="" title="Check the validity of this site&#8217;s HTML" class="zen-validate-html">HTML</a>
        <a href="" title="Check the validity of this site&#8217;s CSS" class="zen-validate-css">CSS</a>
        <a href="" title="View the Creative Commons license of this site: Attribution-NonCommercial-ShareAlike." class="zen-license">CC</a>
        <a href="" title="Read about the accessibility of this site" class="zen-accessibility">A11y</a>
        <a href="" title="Fork this site on Github" class="zen-github">GH</a>
      </footer>

    </div>


    <aside class="sidebar" role="complementary">
      <div class="wrapper">

        <div class="design-selection" id="design-selection">
          <h3 class="select">Select a Design:</h3>
          <nav role="navigation">
            <ul>
              <li>
                <a href="?cssfile=/213/213.css" class="design-name">Under the Sea!</a> by                                               <a href="http://www.ericstoltz.com/" class="designer-name">Eric Stoltz</a>
                </li>                                   <li>
                <a href="?cssfile=/212/212.css" class="design-name">Make ’em Proud</a> by                                               <a href="http://skybased.com/" class="designer-name">Michael McAghon and Scotty Reifsnyder</a>
                </li>                                   <li>
                <a href="?cssfile=/211/211.css" class="design-name">Orchid Beauty</a> by                                                <a href="#" class="designer-name">Kevin Addison</a>
                </li>                                   <li>
                <a href="?cssfile=/210/210.css" class="design-name">Oceanscape</a> by                                           <a href="http://www.pixel-house.com.au/" class="designer-name">Justin Gray</a>
                </li>                                   <li>
                <a href="?cssfile=/209/209.css" class="design-name">CSS Co., Ltd.</a> by                                                <a href="http://www.benklemm.de/" class="designer-name">Benjamin Klemm</a>
                </li>                                   <li>
                <a href="?cssfile=/208/208.css" class="design-name">Sakura</a> by                                               <a href="#" class="designer-name">Tatsuya Uchida</a>
                </li>                                   <li>
                <a href="?cssfile=/207/207.css" class="design-name">Kyoto Forest</a> by                                         <a href="http://rpmdesignfactory.com/" class="designer-name">John Politowski</a>
                </li>                                   <li>
                <a href="?cssfile=/206/206.css" class="design-name">A Walk in the Garden</a> by                                         <a href="http://users.skynet.be/bk316398/temp.html" class="designer-name">Simon Van Hauwermeiren</a>
            </li>                                   </ul>
          </nav>
        </div>

        <div class="design-archives" id="design-archives">
          <h3 class="archives">Archives:</h3>
          <nav role="navigation">
            <ul>
              <li class="next">
                <a href="?cssfile=/001/001.css&amp;page=1">
                  Next Designs <span class="indicator">&rsaquo;
                  </a>
                </li>
                <li class="viewall">
                  <a href="" title="View every submission to the Zen Garden.">
                    View All Designs                                                        </a>
                </li>
              </ul>
            </nav>
          </div>

          <div class="zen-resources" id="zen-resources">
            <h3 class="resources">Resources::</h3>
            <ul>
              <li class="view-css">
                <a href="/001/001.css" title="View the source CSS file of the currently-viewed design.">
                  View This Design&#8217;s <abbr title="Cascading Style Sheets">CSS</abbr>                                                </a>
              </li>
              <li class="css-resources">
                <a href="" title="Links to great sites with information on using CSS.">
                  <abbr title="Cascading Style Sheets">CSS</abbr> Resources                                               </a>
              </li>
              <li class="zen-faq">
                <a href="" title="A list of Frequently Asked Questions about the Zen Garden.">
                  <abbr title="Frequently Asked Questions">FAQ</abbr>                                             </a>
              </li>
              <li class="zen-submit">
                <a href="" title="Send in your own CSS file.">
                  Submit a Design                                         </a>
              </li>
              <li class="zen-translations">
                <a href="" title="View translated versions of this page.">
                  Translations                                            </a>
              </li>
            </ul>
          </div>
        </div>
      </aside>


    </div>

    <!--

    These superfluous divs/spans were originally provided as catch-alls to add extra imagery.
    These days we have full ::before and ::after support, favour using those instead.
    These only remain for historical design compatibility. They might go away one day.

    -->
    <div class="extra1"></div><div class="extra2"></div><div class="extra3"></div>
    <div class="extra4"></div><div class="extra5"></div><div class="extra6"></div>